name: Build and Publish Docker Image

# Triggers when a git tag that starts with 'v' is pushed
on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_REGISTRY: ghcr.io/tallfurryman
  IMAGE_NAME: codex-tools

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git describe in IMAGE_TAG

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the image for the pushed tag and push to Docker Hub.
      # We tag the image with the git tag (e.g. v1.0) and :latest for convenience.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
